[build]
builder = "NIXPACKS"
buildCommand = "npm run build:backend"

[deploy]
startCommand = "npx prisma db push --schema=backend/schema.prisma --accept-data-loss --force-reset && npm run start:backend"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
